[package]
name = "qullzz/qullutility"
description = "A short summary of your code library."
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
realm = "shared"

[dependencies]
